name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clean Install Dependencies
        run: |
          npm cache clean --force
          npm ci

      - name: Clean Build Directory
        if: runner.os == 'Windows'
        run: if exist build rmdir /s /q build
        shell: cmd

      - name: Clean Build Directory (Unix)
        if: runner.os != 'Windows'
        run: rm -rf build
        shell: bash

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true
          force: true
